
//------------------- Users --------------------
//getting all
GET http://localhost:3000/users

###
//getting one
GET http://localhost:3000/users

###
GET http://localhost:3000/users/checkValid/Ya Gwon

###
POST http://localhost:3000/users/signUp/Ya Gwon/15931

###
GET http://localhost:3000/groups/showGroup
//show 속한 그룹 id, 그룹 이름, 사용자 id, 사용자 이름

### folderid
GET http://localhost:3000/folders/showUserName/1


### groupid
GET http://localhost:3000/folders/showFolder/1

###
GET http://localhost:3000/folders/showFolderImage

###
POST http://localhost:3000/groups/makeGroup

###
GET http://localhost:3000/groups/exitGroup

###
POST http://localhost:3000/folders/makeFolder/DG1/축구/월드컵 경기장

###
POST http://localhost:3000/groups

//create one
POST http://localhost:3000/users
Content-Type: application/json

{
    "userName": "jilly",
	"userPWD": "1249",
	"groupId": [{
        "groupId": 

    }]
        
    
}


###
//updateing one
PATCH http://localhost:3000/users
Content-Type: application/json

{
    "userId" : "onew",
    "userPWD" : "1214"
}

###
//deleting one 
DELETE http://localhost:3000/users/60278c7edcbd4f1950981852


####################################################
//------------------- Groups --------------------
//getting all
GET http://localhost:3000/groups

###
//getting one
GET http://localhost:3000/groups/6023ff248a3dfd486a846e4d

###
//create one
POST http://localhost:3000/groups
Content-Type: application/json

{
    "groupName" : "몰입 캠프"
}


###
//updateing one
PATCH http://localhost:3000/groups/6023fc3b5b35c64811faa512
Content-Type: application/json

{
    "userId" : "onew",
    "userPWD" : "1214"
}

###
//deleting one 
DELETE http://localhost:3000/groups/60278c7edcbd4f1950981852

#########################################################
//------------------- Folders --------------------
//getting all
GET http://localhost:3000/folders

###
//getting one
GET http://localhost:3000/folders/6023ff248a3dfd486a846e4d

###
//create one
POST http://localhost:3000/folders
Content-Type: application/json

{
    "folderName": "힐링 모임",
    "location" : "가평"
    //"imageUrl" : ["whkldflw image url", "whkldflw image url1", "whkldflw image url2"]
}


###
//updateing one
PATCH http://localhost:3000/folders/602802f5bdd44f2fbc198e69
Content-Type: application/json

{
    "folderName" : "20.10.20",
    "location" : "제주도",
    ""
}

###
//deleting one 
DELETE http://localhost:3000/folders/3